[phases.setup]
nixPkgs = [
  'php82',
  'php82Packages.composer',
  'php82Extensions.pcntl',
  'php82Extensions.pdo_pgsql',
  'php82Extensions.pgsql',
  'php82Extensions.mbstring',
  'php82Extensions.openssl',
  'nodejs_20'
]

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction',
  'npm install'
]

[phases.build]
cmds = [
  'npm run build'
]